# Use YAML or MYSQL
# If it is an invalid type it will use the YAML
storage: YAML
mysql:
  host: localhost
  port: '3306'
  dbname: mcserver
  username: root
  password: ''

messages:
  Souls: '&aYou have &6{souls} &asouls'
  withoutsouls: '&cYou do not have enough souls to make this purchase.'
# message that will appear when the player gains a soul
  playermessage: '&aYou killed &6{player} &aand won 1 soul'
# message that will appear when the player types /addsouls /setsouls /removesouls
  withoutpermission: '&cYou are not allowed to use this'

configs:
  npc:
   name: '&aSouls Shop'
# use the name of the player you want by the skin that when you give the command /setnpc will be set!
   skin: 'Death'
  ofsoulswhilekillingmob: false
  playermobchance: 0.20
  playermobsouls: 1
  playermessagemob: '&aYou killed a mob and won 1 soul.'
# Number of souls seated when the player first enters the server
# to disable just leave 0
  souls: 10
  playersouls: 1
  playerchance: 0.10
vip:
  vip1:
   name: 'vip1'
   souls: 2
# chance to drop the soul to the player who has the permission dksouls.vip
# ps: the top chance did not affect the VIP!
   chance: 0.25
   message: '&aYou killed &6{player} &aand won 2 soul'
   permission: 'dksouls.vip1'
  vip2:
   name: 'vip2'
   souls: 3
# chance to drop the soul to the player who has the permission dksouls.vip
# ps: the top chance did not affect the VIP!
   chance: 0.40
   message: '&aYou killed &6{player} &aand won 3 soul'
   permission: 'dksouls.vip2'
  vip3:
   name: 'vip3'
   souls: 4
# chance to drop the soul to the player who has the permission dksouls.vip
# ps: the top chance did not affect the VIP!
   chance: 0.60
   message: '&aYou killed &6{player} &aand won 4 soul'
   permission: 'dksouls.vip3'
   
  
Config:
    InventorySize: 27
    InventoryTitle: '&eMenu of souls'
Items:
     ShopMenu:
        Display: '&aShop Menu'
        Slot: 13
        Item: 340
        OpenShopInventory: true
        Lore: 
        - '&e Open the Soul Shop'
        - '&e and buy various items'
        - '&e with their souls'
        - ''
     Stats:
        Display: '&aStats'
        Slot: 15
        Item: 397
        OpenShopInventory: false
        Lore: 
        - '&a Hello {player}'
        - '&f* &eYour status&f *'
        - '&e Souls: &f{souls}'
        - '&e These are your '
        - '&e current status'
        - ''
